<template>
  <section>
    <div>
      <NavBar></NavBar>
      <ApioLogo></ApioLogo>
      <Contacts></Contacts>
      <Uvu></Uvu>
      <Skills></Skills>
      <Footer></Footer>
    </div>
  </section>
</template>
